server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: quatrov-app-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: quatrov-delivery # Tag para você achar seu app no Grafana
          __path__: /var/log/quatrov/*.log # O Promtail vai vigiar os arquivos dessa pasta