# Configura\u00e7\u00f5es do canal de SA\u00cdDA (Producer - PedidoResource)
mp.messaging.outgoing.pedidos-saida.connector=smallrye-kafka
mp.messaging.outgoing.pedidos-saida.topic=pedidos-recebidos
mp.messaging.outgoing.pedidos-saida.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

# Configura\u00e7\u00f5es do canal de ENTRADA (Consumer - PedidoConsumer)
mp.messaging.incoming.pedidos-entrada.connector=smallrye-kafka
mp.messaging.incoming.pedidos-entrada.topic=pedidos-recebidos
mp.messaging.incoming.pedidos-entrada.value.deserializer=org.sparrow.study.quatrov.inbound.messaging.deserializer.PedidoDeserializer