# Configura\u00e7\u00f5es do canal de SA\u00cdDA (Producer - PedidoResource)
mp.messaging.outgoing.pedidos-saida.connector=smallrye-kafka
mp.messaging.outgoing.pedidos-saida.topic=pedidos-recebidos
mp.messaging.outgoing.pedidos-saida.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

# Configura\u00e7\u00f5es do canal de ENTRADA (Consumer - PedidoConsumer)
mp.messaging.incoming.pedidos-entrada.connector=smallrye-kafka
mp.messaging.incoming.pedidos-entrada.topic=pedidos-recebidos
mp.messaging.incoming.pedidos-entrada.value.deserializer=org.sparrow.study.quatrov.integrations.messaging.inbound.deserializer.PedidoDeserializer

# Configura\u00e7\u00e3o do Banco de Dados H2
quarkus.datasource.db-kind=h2
quarkus.datasource.username=sa
quarkus.datasource.password=
quarkus.datasource.jdbc.url=jdbc:h2:mem:DB_QUATROV;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

# Estrat\u00e9gia de gera\u00e7\u00e3o do Banco (Drop and Create a cada inicializa\u00e7\u00e3o em Dev)
# ADICIONE ESTA LINHA ATUALIZADA:
%dev.quarkus.hibernate-orm.schema-management.strategy = drop-and-create

# Mostrar os comandos SQL no console (Excelente para estudar o que o Panache est\u00e1 fazendo)
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.log.bind-parameters=true

# Habilita o log em arquivo
quarkus.log.file.enable=true
# Caminho onde o arquivo ser\u00e1 gerado (ele vai criar a pasta 'logs' na raiz automaticamente)
quarkus.log.file.path=../logs/quatrov.log
# Formato profissional com o TraceID embutido tanto no console quanto no arquivo
quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c{3.}] (%t) [TraceID: %X{traceId}] %m%n
quarkus.log.file.format=%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c{3.}] (%t) [TraceID: %X{traceId}] %m%n